### ISSUE TITLE
Análise Estrutura

### ISSUE THREAD

**Issue by atiladelcanton** [beerandcodeteam/paymentgateway#1]
# Análise Estrutura

Debater, com a comunidade, qual será a arquitetura abordada para esse projeto, e equalizar com todos os envolvidos sobre parte mais técnica de utilização da Estrutura

- [ ] Qual Padrão Arquitetural será empregado
- [ ] Quais Padronizações de código e commit será abordada, caso seja abordada alguma

**Comment by robertotcestari** [comment]
Eu voto em um projeto para laravel. Seria interessante se desse para integrar com (ou extender do) Cashier (que é o pacote oficial)

**Comment by icarojobs** [comment]
Eu voto em fazer um pacote mesmo, primeiro porque tem muita gente que não sabe desenvolver um pacote composer/laravel e segundo que vamos aprender muito mais se desenvolvermos um do zero do que estender um existente. Se o foco é aprender, acredito que fazer um do zero (ainda que se espelhando em outros), será bem melhor para a comunidade.

Mais é aquilo né....o que a maioria decidir, está decidido.

**Comment by devatreides** [comment]
Bom, nesse ponto posso só colocar lenha na discussão hehe. Existe a óbvia vantagem de se usar a estrutura já construída do cashier e economizar tempo no desenvolvimento de funções mais básicas. Isso também condiciona o pacote às atualizações do cashier e suas possíveis mudanças. O mesmo ocorre se a decisão for por criar um pacote especificamente para Laravel. 

Particulamente, gosto da ideia de se criar do zero com o intuito de que os envolvidos consigam acompanhar e construir um conhecimento mais sólido em vários pontos (gateways, projetos, git, composer, patterns), mas entendo perfeitamente a visão de se reaproveitar algo bem estruturado e já pronto.

**Comment by lamarques** [comment]
Sou mais da ideia de construir um pacote que possa ser usado em qualquer aplicação. sem a dependencia de um framework seguindo as premissas da comunidade php. Afinal, para isso que foi criado o composer.

**Comment by robertotcestari** [comment]
Se for fazer em php puro:  https://github.com/nunomaduro/skeleton-php

**Comment by icarojobs** [comment]
> Se for fazer em php puro: https://github.com/nunomaduro/skeleton-php

Muito bom Beto!!!! Bora seguir esse boilerplate ae.

**Comment by fsrocha-dev** [comment]
Eu voto por fazer um pacote otimizado para o Laravel.

**Comment by atiladelcanton** [comment]
Vamos, analisar com base em uma enquete?

https://forms.gle/m9iPM2pJZUVYMMN99

**Comment by robertotcestari** [comment]
boa!

**Comment by marquesini** [comment]
Pessoal, achei uma biblioteca que já faz isso:
https://omnipay.thephpleague.com/

Ela é feita em php puro e é bem madura. Então, para esse formato, a comunidade já está bem servida. Podemos utilizá-la como base de conhecimento.

Depois de ter visto ela, acho que extender o Cashier com novos gateways seria mais viável para a nossa iniciativa.

**Comment by robertotcestari** [comment]
Legl heim. Vi q tem pagar.me, mas acho q faltam varios brasileiros

Em sex, 3 de jul de 2020 23:15, Leandro Marquesini <notifications@github.com>
escreveu:

**Comment by atiladelcanton** [comment]
Bacana, esse cara mais ai cai em um ponto que e pessoal **MEU**, por que reaproveitar ou usar pacotes gringos e não fazer um top tanto quanto porem 100% brazuka, visando os nossos desenvolvedores ?

Documentação pt-br etc...

Igual a comunidade Flutter, o brasil ta sendo top com pacotes, o Mobx da flutterando o pacote Get feito por BR....

Podemos usar os gringos para ver o que não tem e fazer melhor.
