### ISSUE TITLE
Gatway Iniciais

### ISSUE THREAD

**Issue by atiladelcanton** [beerandcodeteam/paymentgateway#2]
Definirmos qual ou quais serão os os Gateway que inicializamos a integração com o sistema, acho que podemos priorizar o Gateway para escolha por alguns pontos:

* Mais Utilizado
* Documentação Mais clara e objetiva

**Comment by icarojobs** [comment]
Acredito que poderíamos começar apenas com Pagseguro. Após implementar o Pagseguro bem feito, poderíamos fazer o Mercado Pago e GerenciaNet mais por questão de documentação de menor burocracia. Depois só seguir a estrutura/implementação pra outros (Stripe, Pagar.Me, etc.)
