### ISSUE TITLE
Definição de Funcionalidades

### ISSUE THREAD

**Issue by atiladelcanton** [beerandcodeteam/paymentgateway#3]
Definir, as principais e iniciais funcionalidades que existiram no projeto, afim de podermos trabalhar com pequenas features e manter o projeto sempre com atualização.

**Comment by devatreides** [comment]
Quanto a essa parte, acho que seria interessante um exercício de reflexão. Pensar primeiro e descrever ou listar em passos/etapas como o usuário usaria o pacote. Descrevendo o fluxo de uso do usuário nos dá uma visão boa do que realmente pretende-se construir. Depois de termos isso claro, podemos pensar em todas as tarefas necessárias para atender essa nossa "expectativa" sobre o uso do pacote. 

Principalmente quem tem mais experiência com essas integrações, responder:

- Qual a melhor forma de se integrar um metodo de pagamento no projeto?
ou
- Quais foram os problemas com outros pacotes/implementações que gostaria de resolver aqui?
ou
- Como eu gostaria de manipular um gateway no meu Service/Controller?

Digo isso pq é bom a gente ter bem claro o objetivo final, assim, a gente ja consegue desenvolver de forma estruturada e pensando na usabilidade.

Bom, é uma sugestão, acho que ajuda bastante a gente pensar assim na hora de construir um pacote, ter uma ideia (não precisa ser definida obviamente) de como gostaria de usar e tentar estruturar a partir disso. É isso  hehe.

Ex:
*definir os dados no service/controller com $gateway->use(PagSeguro::class)*

*usar função do gateway com $gateway->funcao();*

*trocar de gateway com $gateway->change(NovoGateway::class)*

____________________________
*p.s. os exemplos são sem noção, eu sei, mas era só pra ilustrar o que eu tentei explicar mais acima*

**Comment by marquesini** [comment]
Acho que vale a pena considerar também que os Gateways podem lançar novas versões até mesmo durante o desenvolvimento desse projeto. Se o pacote considerar a versão na hora de instanciar o gateway, teremos flexibilidade para continuar atualizando o nosso projeto sem afetar as versões estáveis de cada implementação.

**Comment by fsrocha-dev** [comment]
@marquesini , mas seria viável manter implementações para diferentes versões do mesmo Gateway ?

**Comment by marquesini** [comment]
@fsrocha-dev Desenvolveríamos para a versão atual dos Gateways escolhidos. Quando surgirem novas versões, o que já tivermos pronto pode ficar incompatível. Para não alterar código de versões legadas e continuarmos evoluindo, imagino que ao surgirem novas apis's de cada Gateway precisaremos fazer uma nova implementação para cada uma. Isso também facilitará que os clientes desse projeto possam atualizar a versão com mais facilidade.

Exemplo para o usuário:

$gateway = PaymentGatway::create("pagseguro4"); // instância a versão correspondente.
// depois de um tempo...
$gateway = PaymentGatway::create("pagseguro5"); // A nossa versão legada deixaria de ter suporte e apenas a nova seria atualizada.

É algo que passou pela minha cabeça, nunca fiz nada parecido na prática. Se acharem viável podemos amadurecer essa ideia.
